http:
  host: "0.0.0.0"
  port: "8081"
  path: "/"

db:
  maxPoolSize: "10"
  minPoolSize: "2"
  accIncrement: "1"
  psCacheSize: "5"
  maxWait: "30"
  maxIdleTime: "0"
  maxStatements: "0"
  frecuency: "10"

sfdc:
  frecuency: "10"

mac:
  send_batches_size: "2"
  use_openai: "true"
